//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnvironmentVariableExplorer.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EnvironmentVariableExplorer.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environment Variable Explorer.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete environment variable.
        /// </summary>
        public static string DeleteEnvironmentVariableError {
            get {
                return ResourceManager.GetString("DeleteEnvironmentVariableError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete.
        /// </summary>
        public static string DialogConfirmDeletionMessage {
            get {
                return ResourceManager.GetString("DialogConfirmDeletionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Deletion.
        /// </summary>
        public static string DialogConfirmDeletionTitle {
            get {
                return ResourceManager.GetString("DialogConfirmDeletionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get environment variables for.
        /// </summary>
        public static string GetEnvironmentVariablesByTargetError {
            get {
                return ResourceManager.GetString("GetEnvironmentVariablesByTargetError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid target selected.
        /// </summary>
        public static string InvalidEnvironmentVariableTargetError {
            get {
                return ResourceManager.GetString("InvalidEnvironmentVariableTargetError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading environment variables.
        /// </summary>
        public static string LoadEnvironmentVariablesError {
            get {
                return ResourceManager.GetString("LoadEnvironmentVariablesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to set environment variable &apos;{0}&apos;.
        /// </summary>
        public static string SetEnvironmentVariableError {
            get {
                return ResourceManager.GetString("SetEnvironmentVariableError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to environment variables are only supported on Windows..
        /// </summary>
        public static string SetEnvironmentVariablePlatformError {
            get {
                return ResourceManager.GetString("SetEnvironmentVariablePlatformError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only Process-level variables can be added on this platform..
        /// </summary>
        public static string SnackbarAddRowPlatformWarning {
            get {
                return ResourceManager.GetString("SnackbarAddRowPlatformWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change saved.
        /// </summary>
        public static string SnackbarChangeSaved {
            get {
                return ResourceManager.GetString("SnackbarChangeSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete.
        /// </summary>
        public static string SnackbarDeleteFailed {
            get {
                return ResourceManager.GetString("SnackbarDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted successfully.
        /// </summary>
        public static string SnackbarDeleteSuccess {
            get {
                return ResourceManager.GetString("SnackbarDeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save.
        /// </summary>
        public static string SnackbarFailedToSave {
            get {
                return ResourceManager.GetString("SnackbarFailedToSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target.
        /// </summary>
        public static string Target {
            get {
                return ResourceManager.GetString("Target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
    }
}
